// Draws the app icon from the website's favicon (../../public/favicon.svg), so the app and the
// site share one icon.
//
//   node scripts/make-icons.mjs
//
// Writes:
//  - Android: an adaptive icon (mipmap-anydpi-v26 plus two vector drawables) for Android 8+, with
//    a monochrome layer for themed icons on Android 13+, and PNGs for Android 7.
//  - iOS: every size listed in AppIcon.appiconset/Contents.json. iOS rounds the corners itself and
//    rejects transparency, so these fill the whole square.
//  - android/app/src/main/ic_launcher-playstore.png, the 512 px icon the Play Console asks for.
//
// The PNGs are drawn here rather than by an SVG converter so the script needs no packages. It
// reads the favicon's rounded square, its two-stop gradient and its stroked chevrons; run it again
// after changing favicon.svg.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { crc32, deflateSync } from 'node:zlib';

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const faviconPath = join(appRoot, '..', '..', 'public', 'favicon.svg');
const androidRes = join(appRoot, 'android', 'app', 'src', 'main', 'res');
const iosIconSet = join(
  appRoot,
  'ios',
  'ofctools',
  'Images.xcassets',
  'AppIcon.appiconset',
);

const icon = readFavicon(readFileSync(faviconPath, 'utf8'));

// ---- Android ----

const DENSITIES = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
for (const [density, size] of Object.entries(DENSITIES)) {
  const dir = join(androidRes, `mipmap-${density}`);
  writeFileSync(join(dir, 'ic_launcher.png'), render(icon, size, 'rounded'));
  writeFileSync(
    join(dir, 'ic_launcher_round.png'),
    render(icon, size, 'circle'),
  );
}

// Adaptive icon layers are 108 dp; launchers show the middle 72 dp through their own mask, so
// the favicon's square is fitted to that and the gradient runs corner to corner across it.
const LAYER = 108;
const SHOWN = 72;
const k = SHOWN / icon.rect.width;
const toDp = (x, y) => [
  LAYER / 2 + (x - icon.rect.x - icon.rect.width / 2) * k,
  LAYER / 2 + (y - icon.rect.y - icon.rect.height / 2) * k,
];
const [gx1, gy1] = toDp(...icon.gradient.from);
const [gx2, gy2] = toDp(...icon.gradient.to);
const chevronPath = icon.lines
  .map(points =>
    points.map((p, i) => `${i ? 'L' : 'M'}${fmt(toDp(...p))}`).join(''),
  )
  .join('');

const vector = body => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/make-icons.mjs from the website's favicon.svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="${LAYER}dp"
    android:height="${LAYER}dp"
    android:viewportWidth="${LAYER}"
    android:viewportHeight="${LAYER}">
${body}
</vector>
`;
const gradientItems = icon.gradient.stops
  .map(({ offset, color }) => {
    const stop = `android:offset="${fmt(offset)}"`;
    return `                <item ${stop} android:color="${hex(color)}" />`;
  })
  .join('\n');
writeFileSync(
  join(androidRes, 'drawable', 'ic_launcher_background.xml'),
  vector(`    <path android:pathData="M0,0h${LAYER}v${LAYER}h-${LAYER}z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="${fmt(gx1)}"
                android:startY="${fmt(gy1)}"
                android:endX="${fmt(gx2)}"
                android:endY="${fmt(gy2)}">
${gradientItems}
            </gradient>
        </aapt:attr>
    </path>`),
);
writeFileSync(
  join(androidRes, 'drawable', 'ic_launcher_foreground.xml'),
  vector(`    <path
        android:pathData="${chevronPath}"
        android:strokeColor="${hex(icon.stroke)}"
        android:strokeWidth="${fmt(icon.strokeWidth * k)}"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />`),
);
const adaptive = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/make-icons.mjs from the website's favicon.svg. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
`;
const anydpi = join(androidRes, 'mipmap-anydpi-v26');
mkdirSync(anydpi, { recursive: true });
writeFileSync(join(anydpi, 'ic_launcher.xml'), adaptive);
writeFileSync(join(anydpi, 'ic_launcher_round.xml'), adaptive);

writeFileSync(
  join(appRoot, 'android', 'app', 'src', 'main', 'ic_launcher-playstore.png'),
  render(icon, 512, 'square'),
);

// ---- iOS ----

const contentsPath = join(iosIconSet, 'Contents.json');
const contents = JSON.parse(readFileSync(contentsPath, 'utf8'));
contents.images = contents.images.map(({ filename: _old, ...entry }) => {
  const points = Number(entry.size.split('x')[0]);
  const scale = Number(entry.scale.replace('x', ''));
  const filename =
    entry.idiom === 'ios-marketing'
      ? `icon-${points}.png`
      : `icon-${points}@${scale}x.png`;
  writeFileSync(
    join(iosIconSet, filename),
    render(icon, points * scale, 'square', 3),
  );
  return { filename, ...entry };
});
writeFileSync(contentsPath, JSON.stringify(contents, null, 2) + '\n');

console.log('App icons written for Android and iOS.');

// ---- Reading the favicon ----

function readFavicon(svg) {
  const attrs = tag => {
    const m = svg.match(new RegExp(`<${tag}\\b([^>]*)>`));
    if (!m) throw new Error(`favicon.svg has no <${tag}>`);
    return Object.fromEntries(
      [...m[1].matchAll(/([\w-]+)="([^"]*)"/g)].map(a => [a[1], a[2]]),
    );
  };
  const [, , viewWidth] = attrs('svg').viewBox.split(/\s+/).map(Number);
  const r = attrs('rect');
  const rect = {
    x: Number(r.x ?? 0),
    y: Number(r.y ?? 0),
    width: Number(r.width),
    height: Number(r.height),
    radius: Number(r.rx ?? 0),
  };
  const g = attrs('linearGradient');
  // Gradient ends are fractions of the rect (the SVG default, objectBoundingBox).
  const at = (fx, fy) => [rect.x + fx * rect.width, rect.y + fy * rect.height];
  const stops = [...svg.matchAll(/<stop\b([^>]*)>/g)].map(m => ({
    offset: Number(m[1].match(/offset="([^"]*)"/)[1]),
    color: rgb(m[1].match(/stop-color="([^"]*)"/)[1]),
  }));
  const p = attrs('path');
  const lines = p.d
    .split('M')
    .filter(Boolean)
    .map(part => {
      if (/[a-z]/i.test(part))
        throw new Error('favicon.svg path: only M and implicit lines are read');
      const n = part
        .trim()
        .split(/[\s,]+/)
        .map(Number);
      return Array.from({ length: n.length / 2 }, (_, i) => [
        n[2 * i],
        n[2 * i + 1],
      ]);
    });
  return {
    viewWidth,
    rect,
    gradient: {
      from: at(Number(g.x1 ?? 0), Number(g.y1 ?? 0)),
      to: at(Number(g.x2 ?? 1), Number(g.y2 ?? 0)),
      stops,
    },
    lines,
    stroke: rgb(p.stroke),
    strokeWidth: Number(p['stroke-width']),
  };
}

function rgb(value) {
  let h = value.replace('#', '');
  if (h.length === 3) h = [...h].map(c => c + c).join('');
  return [0, 2, 4].map(i => parseInt(h.slice(i, i + 2), 16));
}

function hex(c) {
  return (
    '#FF' +
    c
      .map(v => v.toString(16).padStart(2, '0'))
      .join('')
      .toUpperCase()
  );
}

function fmt(value) {
  if (Array.isArray(value)) return value.map(fmt).join(',');
  return String(Math.round(value * 100) / 100);
}

// ---- Drawing ----

// shape: 'rounded' is the favicon as the website shows it, 'circle' swaps the rounded square for a
// circle, and 'square' crops to the rounded square's box with no corners or transparency (stores
// and iOS apply their own mask).
function render(art, size, shape, channels = 4) {
  const { rect } = art;
  const cropped = shape === 'square';
  const scale = size / (cropped ? rect.width : art.viewWidth);
  const ox = cropped ? rect.x : 0;
  const oy = cropped ? rect.y : 0;
  const cx = rect.x + rect.width / 2;
  const cy = rect.y + rect.height / 2;
  const half = rect.width / 2;
  const [x1, y1] = art.gradient.from;
  const [x2, y2] = art.gradient.to;
  const gdx = x2 - x1;
  const gdy = y2 - y1;
  const glen = gdx * gdx + gdy * gdy;
  const stops = art.gradient.stops;
  const segments = art.lines.flatMap(points =>
    points.slice(1).map((p, i) => [points[i], p]),
  );
  const strokeHalf = art.strokeWidth / 2;

  const out = Buffer.alloc(size * size * channels);
  for (let py = 0; py < size; py++) {
    for (let px = 0; px < size; px++) {
      const x = ox + (px + 0.5) / scale;
      const y = oy + (py + 0.5) / scale;

      let base;
      if (shape === 'rounded')
        base = roundedRectDistance(x - cx, y - cy, half, rect.radius);
      else if (shape === 'circle') base = Math.hypot(x - cx, y - cy) - half;
      else base = -Infinity;
      const baseAlpha = coverage(base * scale);

      let line = Infinity;
      for (const [a, b] of segments)
        line = Math.min(line, segmentDistance(x, y, a, b));
      const lineAlpha = coverage((line - strokeHalf) * scale);

      const t = Math.min(
        1,
        Math.max(0, ((x - x1) * gdx + (y - y1) * gdy) / glen),
      );
      const fill = gradientAt(stops, t);
      const alpha = lineAlpha + baseAlpha * (1 - lineAlpha);
      const i = (py * size + px) * channels;
      for (let c = 0; c < 3; c++) {
        const v = alpha
          ? (art.stroke[c] * lineAlpha +
              fill[c] * baseAlpha * (1 - lineAlpha)) /
            alpha
          : 0;
        out[i + c] = Math.round(v);
      }
      if (channels === 4) out[i + 3] = Math.round(alpha * 255);
    }
  }
  return encodePng(size, size, channels, out);
}

// Signed distance in pixels to an edge, turned into how much of the pixel is covered.
function coverage(distance) {
  return Math.min(1, Math.max(0, 0.5 - distance));
}

function roundedRectDistance(dx, dy, half, radius) {
  const qx = Math.abs(dx) - half + radius;
  const qy = Math.abs(dy) - half + radius;
  return (
    Math.hypot(Math.max(qx, 0), Math.max(qy, 0)) +
    Math.min(Math.max(qx, qy), 0) -
    radius
  );
}

function segmentDistance(x, y, [ax, ay], [bx, by]) {
  const dx = bx - ax;
  const dy = by - ay;
  const t = Math.min(
    1,
    Math.max(0, ((x - ax) * dx + (y - ay) * dy) / (dx * dx + dy * dy)),
  );
  return Math.hypot(x - ax - t * dx, y - ay - t * dy);
}

function gradientAt(stops, t) {
  if (t <= stops[0].offset) return stops[0].color;
  for (let i = 1; i < stops.length; i++) {
    const a = stops[i - 1];
    const b = stops[i];
    if (t <= b.offset) {
      const f = (t - a.offset) / (b.offset - a.offset || 1);
      return a.color.map((v, c) => v + (b.color[c] - v) * f);
    }
  }
  return stops[stops.length - 1].color;
}

function encodePng(width, height, channels, pixels) {
  const stride = width * channels;
  const raw = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    pixels.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }
  const header = Buffer.alloc(13);
  header.writeUInt32BE(width, 0);
  header.writeUInt32BE(height, 4);
  header[8] = 8;
  header[9] = channels === 4 ? 6 : 2;
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk('IHDR', header),
    pngChunk('IDAT', deflateSync(raw, { level: 9 })),
    pngChunk('IEND', Buffer.alloc(0)),
  ]);
}

function pngChunk(type, data) {
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}
